//
//  DefaultExercises.swift
//  Workout App
//
//  Created by Jonathan Young on 6/26/25.
//

import Foundation

let DEFAULT_EXERCISES: [Exercise] = [
    Exercise(name: "Barbell Back Squat", note: "", exerciseDescription: "A foundational lower body lift.", howTo: ["Place bar on upper back", "Squat until thighs are parallel", "Drive up through heels"], muscleType: .quadriceps, secondaryMuscleTypes: [.glutes, .hamstrings], equipmentType: .barbell, exerciseType: .weightedReps),
    Exercise(name: "Push-Up", note: "", exerciseDescription: "Bodyweight pressing movement for upper body.", howTo: ["Lower chest to floor", "Push back up with arms"], muscleType: .chest, secondaryMuscleTypes: [.triceps, .shoulders], equipmentType: .bodyweight, exerciseType: .bodyweightReps),
    Exercise(name: "Plank", note: "", exerciseDescription: "Isometric core hold.", howTo: ["Hold forearm plank", "Keep spine neutral"], muscleType: .abdominals, secondaryMuscleTypes: [.obliques], equipmentType: .none, exerciseType: .timeBased),
    Exercise(name: "Pull-Up", note: "", exerciseDescription: "Vertical pulling motion for upper body strength.", howTo: ["Hang from bar", "Pull chin over bar", "Lower down slowly"], muscleType: .lats, secondaryMuscleTypes: [.biceps, .upperBack], equipmentType: .bodyweight, exerciseType: .bodyweightReps),
    Exercise(name: "Deadlift", note: "", exerciseDescription: "Full-body pulling movement.", howTo: ["Grip barbell over midfoot", "Stand up straight", "Lower bar back to floor"], muscleType: .hamstrings, secondaryMuscleTypes: [.glutes, .erectorSpinae], equipmentType: .barbell, exerciseType: .weightedReps),
    Exercise(name: "Dumbbell Shoulder Press", note: "", exerciseDescription: "Overhead pressing movement.", howTo: ["Press dumbbells overhead", "Control downward motion"], muscleType: .shoulders, secondaryMuscleTypes: [.triceps], equipmentType: .dumbbells, exerciseType: .weightedReps),
    Exercise(name: "Wall Sit", note: "", exerciseDescription: "Isometric quad endurance drill.", howTo: ["Slide down wall until thighs are parallel", "Hold position"], muscleType: .quadriceps, secondaryMuscleTypes: [.glutes], equipmentType: .none, exerciseType: .timeBased),
    Exercise(name: "Barbell Bench Press", note: "", exerciseDescription: "Horizontal push movement for chest.", howTo: ["Lower bar to chest", "Press upward"], muscleType: .chest, secondaryMuscleTypes: [.triceps, .shoulders], equipmentType: .barbell, exerciseType: .weightedReps),
    Exercise(name: "Romanian Deadlift", note: "", exerciseDescription: "Posterior chain strength exercise.", howTo: ["Hinge at hips", "Lower bar down legs", "Return upright"], muscleType: .hamstrings, secondaryMuscleTypes: [.glutes, .lowerBack], equipmentType: .barbell, exerciseType: .weightedReps),
    Exercise(name: "Step-Up", note: "", exerciseDescription: "Unilateral lower-body movement.", howTo: ["Step onto box", "Drive through lead leg", "Step down"], muscleType: .glutes, secondaryMuscleTypes: [.quadriceps], equipmentType: .dumbbells, exerciseType: .heightReps),
    Exercise(name: "Jump Rope", note: "", exerciseDescription: "High-intensity cardio drill.", howTo: ["Turn rope", "Jump in rhythm"], muscleType: .cardio, secondaryMuscleTypes: [.calves], equipmentType: .other, exerciseType: .timeOnly),
    Exercise(name: "Lateral Raise", note: "", exerciseDescription: "Deltoid isolation.", howTo: ["Raise arms to side", "Control downward motion"], muscleType: .shoulders, secondaryMuscleTypes: [], equipmentType: .dumbbells, exerciseType: .weightedReps),
    Exercise(name: "Hip Thrust", note: "", exerciseDescription: "Glute-focused lift.", howTo: ["Rest shoulders on bench", "Drive hips up", "Lower under control"], muscleType: .glutes, secondaryMuscleTypes: [.hamstrings], equipmentType: .barbell, exerciseType: .weightedReps),
    Exercise(name: "Box Jump", note: "", exerciseDescription: "Explosive plyometric move.", howTo: ["Jump onto box", "Step down carefully"], muscleType: .quadriceps, secondaryMuscleTypes: [.calves], equipmentType: .none, exerciseType: .heightReps),
    Exercise(name: "Bent-Over Row", note: "", exerciseDescription: "Horizontal pulling for back.", howTo: ["Row bar to ribs", "Control return"], muscleType: .upperBack, secondaryMuscleTypes: [.biceps, .lats], equipmentType: .barbell, exerciseType: .weightedReps),
    Exercise(name: "Lat Pulldown", note: "", exerciseDescription: "Vertical pulling with machine.", howTo: ["Pull bar to chest", "Control return upward"], muscleType: .lats, secondaryMuscleTypes: [.biceps], equipmentType: .machine, exerciseType: .weightedReps),
    Exercise(name: "Bicycle Crunch", note: "", exerciseDescription: "Rotational core exercise.", howTo: ["Alternate elbow to knee"], muscleType: .obliques, secondaryMuscleTypes: [.abdominals], equipmentType: .none, exerciseType: .bodyweightReps),
    Exercise(name: "Tricep Pushdown", note: "", exerciseDescription: "Cable push for triceps.", howTo: ["Push bar down", "Control back up"], muscleType: .triceps, secondaryMuscleTypes: [], equipmentType: .machine, exerciseType: .weightedReps),
    Exercise(name: "Hammer Curl", note: "", exerciseDescription: "Neutral grip bicep curl.", howTo: ["Curl dumbbells with thumbs up", "Lower slowly"], muscleType: .biceps, secondaryMuscleTypes: [.forearms], equipmentType: .dumbbells, exerciseType: .weightedReps),
    Exercise(name: "Leg Press", note: "", exerciseDescription: "Machine-based lower body push.", howTo: ["Push platform", "Control descent"], muscleType: .quadriceps, secondaryMuscleTypes: [.glutes, .hamstrings], equipmentType: .machine, exerciseType: .weightedReps),
    Exercise(name: "Glute Kickback", note: "", exerciseDescription: "Isolated glute contraction.", howTo: ["Kick leg back", "Squeeze glute"], muscleType: .glutes, secondaryMuscleTypes: [], equipmentType: .machine, exerciseType: .weightedReps),
    Exercise(name: "Farmer's Carry", note: "", exerciseDescription: "Grip, core, and posture challenge.", howTo: ["Hold dumbbells at sides", "Walk slowly"], muscleType: .gripStrength, secondaryMuscleTypes: [.traps, .abdominals], equipmentType: .dumbbells, exerciseType: .distanceTime),
    Exercise(name: "Seated Calf Raise", note: "", exerciseDescription: "Targets soleus muscle.", howTo: ["Raise heels", "Control descent"], muscleType: .calves, secondaryMuscleTypes: [], equipmentType: .machine, exerciseType: .weightedReps),
    Exercise(name: "Neck Flexion", note: "", exerciseDescription: "Strengthens neck flexors.", howTo: ["Use band or plate", "Flex neck downward"], muscleType: .neck, secondaryMuscleTypes: [], equipmentType: .plate, exerciseType: .weightedReps),
    Exercise(name: "Band Pull-Apart", note: "", exerciseDescription: "Scapular retraction drill.", howTo: ["Pull band apart", "Squeeze shoulder blades"], muscleType: .traps, secondaryMuscleTypes: [.shoulders], equipmentType: .resistanceBand, exerciseType: .repsOnly),
    Exercise(name: "Incline Dumbbell Curl", note: "", exerciseDescription: "Biceps isolation curl.", howTo: ["Lean back", "Curl dumbbells upward"], muscleType: .biceps, secondaryMuscleTypes: [], equipmentType: .dumbbells, exerciseType: .weightedReps),
    Exercise(name: "Step Count", note: "", exerciseDescription: "Track walking steps per day.", howTo: ["Walk continuously to log steps"], muscleType: .cardio, secondaryMuscleTypes: [.tibialisAnterior], equipmentType: .none, exerciseType: .distanceOnly),
    Exercise(name: "Sled Push", note: "", exerciseDescription: "High-intensity leg and cardio movement.", howTo: ["Push sled forward", "Drive with legs"], muscleType: .quadriceps, secondaryMuscleTypes: [.glutes, .calves], equipmentType: .other, exerciseType: .distanceTime),
    Exercise(name: "Hanging Leg Raise", note: "", exerciseDescription: "Hip flexor and core strength.", howTo: ["Hang from bar", "Lift legs", "Lower slowly"], muscleType: .hipFlexors, secondaryMuscleTypes: [.abdominals], equipmentType: .bodyweight, exerciseType: .bodyweightReps),
    Exercise(name: "Suspension Row", note: "", exerciseDescription: "Bodyweight pulling with suspension bands.", howTo: ["Lean back", "Row handles to chest"], muscleType: .upperBack, secondaryMuscleTypes: [.biceps], equipmentType: .suspensionBand, exerciseType: .bodyweightReps)
]
